name: Testing Maven
run-name: ${{ github.actor }} is doing tests ğŸš€
on: [push]
jobs:
  test-maven:
    runs-on: ubuntu-latest
    steps:
      - name: Check out do cÃ³digo do repositÃ³rio
        uses: actions/checkout@v3
      - name: Mvn test
        run: |
          cd Maven/junit-exemplos
          mvn install
          mvn test
      - run: echo "ğŸ O status do job Ã© ${{ job.status }}."
